# Generated by Django 5.0.14 on 2026-04-19 23:08

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plot_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("site_name", models.CharField(max_length=100)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("eastern_cape", "Eastern Cape"),
                            ("free_state", "Free State"),
                            ("gauteng", "Gauteng"),
                            ("kwazulu_natal", "KwaZulu-Natal"),
                            ("limpopo", "Limpopo"),
                            ("mpumalanga", "Mpumalanga"),
                            ("northern_cape", "Northern Cape"),
                            ("north_west", "North West"),
                            ("western_cape", "Western Cape"),
                            ("other", "Other (Specify)"),
                        ],
                        default="eastern_cape",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("enumerator", models.CharField(max_length=100)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "gps_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "gps_point_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Sequential GPS waypoint for plot center"
                    ),
                ),
                ("plot_radius", models.IntegerField(default=25)),
                (
                    "dist_water_point",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("less_200m", "0-200m (Very close)"),
                            ("200_600m", "200-600m (Moderate distance)"),
                            ("beyond_600m", "Beyond 600m (Distant)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dist_settlement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("less_500m", "0-500m (Very close)"),
                            ("500_1500m", "500m-1.5km (Moderate distance)"),
                            ("beyond_1500m", "More than 1.5km (Remote)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("water_point_notes", models.TextField(blank=True)),
                ("settlement_notes", models.TextField(blank=True)),
                (
                    "forest_type",
                    models.CharField(
                        choices=[
                            ("afrotemperate", "Afrotemperate Forest"),
                            ("thicket", "Albany Thicket"),
                            ("savanna", "Savanna Woodland"),
                            ("grassland", "Grassland"),
                            ("plantation", "Commercial Plantation"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trees_count_est", models.IntegerField(blank=True, null=True)),
                (
                    "habitat_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pristine", "Pristine/Natural"),
                            ("good", "Good Condition"),
                            ("moderate", "Moderate Degradation"),
                            ("degraded", "Degraded"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "canopy_cover",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "carbon_standard",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ccb", "CCB (Climate, Community & Biodiversity)"),
                            ("vcs", "VCS (Verified Carbon Standard)"),
                            ("ccb_vcs", "CCB + VCS"),
                            ("gold", "Gold Standard"),
                            ("planvivo", "Plan Vivo"),
                            ("multiple", "Multiple Standards"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "land_tenure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("communal", "Communal Land"),
                            ("private", "Private Land"),
                            ("state", "State Land"),
                            ("community", "Community Trust"),
                            ("pa", "Protected Area"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "community_consult",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                ("community_name", models.CharField(blank=True, max_length=100)),
                (
                    "ccb_compliance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ccb_level", models.CharField(blank=True, max_length=20)),
                (
                    "gs_sdgs",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pv_community", models.CharField(blank=True, max_length=100)),
                ("pv_scheme", models.CharField(blank=True, max_length=100)),
                (
                    "module_biomass",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        max_length=10,
                    ),
                ),
                (
                    "module_biodiversity",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        max_length=10,
                    ),
                ),
                (
                    "module_soil",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        max_length=10,
                    ),
                ),
                (
                    "module_water",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=10,
                    ),
                ),
                (
                    "module_socioeconomic",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "plot_id"],
                "indexes": [
                    models.Index(
                        fields=["forest_type"], name="collect_plo_forest__dc51f6_idx"
                    ),
                    models.Index(fields=["date"], name="collect_plo_date_5de78e_idx"),
                    models.Index(
                        fields=["province"], name="collect_plo_provinc_387e92_idx"
                    ),
                    models.Index(
                        fields=["module_water"], name="collect_plo_module__765f56_idx"
                    ),
                    models.Index(
                        fields=["module_socioeconomic"],
                        name="collect_plo_module__df6c88_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocioEconomic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "community_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rural_village", "Rural Village (traditional)"),
                            ("rural_scattered", "Rural (scattered homesteads)"),
                            ("peri_urban", "Peri-Urban"),
                            ("township", "Township"),
                            ("farm_laborer", "Farm Labourer Settlement"),
                            ("communal_area", "Communal/Traditional Authority Area"),
                            ("informal_settlement", "Informal Settlement"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "households_nearby",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "population_estimate",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "tenure_security",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_secure", "Very Secure (freehold/deed)"),
                            ("secure", "Secure (CPAs, Trusts, Communal Permission)"),
                            ("moderate", "Moderate (Permission to Occupy)"),
                            ("insecure", "Insecure (no formal documentation)"),
                            ("disputed", "Disputed (under land claim/court case)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "land_use_current",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("grazing", "Grazing (livestock)"),
                            ("cropland", "Cropland (cultivation)"),
                            ("fallow", "Fallow/Abandoned"),
                            ("forest_reserve", "Forest Reserve/Protected"),
                            ("plantation", "Commercial Plantation"),
                            ("mining", "Mining/Extractive"),
                            ("conservation", "Conservation Area"),
                            ("unoccupied", "Unoccupied/Unused"),
                            ("mixed_use", "Mixed Use"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("land_use_history", models.CharField(blank=True, max_length=200)),
                ("livelihood_activities", models.CharField(blank=True, max_length=300)),
                (
                    "primary_income_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("agriculture", "Agriculture (crops/livestock)"),
                            ("wage_labour", "Wage Labour"),
                            ("social_grants", "Social Grants (SASSA)"),
                            ("remittances", "Remittances"),
                            ("informal_business", "Informal Business"),
                            ("mining", "Mining (formal/informal)"),
                            ("tourism", "Tourism/Conservation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "household_income_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("below_poverty", "Below Food Poverty Line (<R760/month)"),
                            ("low", "Low Income (R760 - R2,500/month)"),
                            ("lower_middle", "Lower-Middle (R2,500 - R5,500/month)"),
                            ("middle", "Middle Income (R5,500 - R15,000/month)"),
                            ("above_middle", "Above Middle (>R15,000/month)"),
                            ("unknown", "Unknown/Declined to Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "community_restoration_awareness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_aware", "Very Aware (active engagement)"),
                            ("aware", "Aware (have heard of it)"),
                            ("somewhat", "Somewhat Aware (limited knowledge)"),
                            ("not_aware", "Not Aware"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "restoration_support",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_supportive", "Very Supportive"),
                            ("supportive", "Supportive"),
                            ("neutral", "Neutral"),
                            ("opposed", "Opposed"),
                            ("very_opposed", "Very Opposed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expected_restoration_benefits",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "willingness_to_participate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unsure", "Unsure/Maybe"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "traditional_leadership_involved",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                (
                    "indigenous_practices_present",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                (
                    "indigenous_practices_types",
                    models.CharField(blank=True, max_length=300),
                ),
                ("traditional_knowledge_notes", models.TextField(blank=True)),
                (
                    "capacity_building_needs",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "job_creation_potential",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_10", "1-10 jobs"),
                            ("11_50", "11-50 jobs"),
                            ("51_100", "51-100 jobs"),
                            ("100_plus", "100+ jobs"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender_balance_participation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mostly_men", "Mostly Male Participants"),
                            ("mostly_women", "Mostly Female Participants"),
                            ("balanced", "Gender Balanced"),
                            ("women_led", "Women-Led"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "restoration_challenges",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "fire_risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low (rare fires)"),
                            ("moderate", "Moderate (occasional fires)"),
                            ("high", "High (frequent fires)"),
                            ("very_high", "Very High (annual/severe fires)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "invasive_species_threats",
                    models.CharField(blank=True, max_length=300),
                ),
                ("socioeconomic_notes", models.TextField(blank=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socioeconomic",
                        to="collect.plot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoilSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_id",
                    models.CharField(
                        choices=[
                            ("p1", "Point 1 (Center)"),
                            ("p2", "Point 2 (North)"),
                            ("p3", "Point 3 (East)"),
                            ("p4", "Point 4 (South)"),
                            ("p5", "Point 5 (West)"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("point_num", models.IntegerField()),
                (
                    "gps_waypoint_number",
                    models.PositiveIntegerField(
                        help_text="GPS waypoint for this soil sample point"
                    ),
                ),
                (
                    "soil_gps",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "depth_class",
                    models.CharField(
                        choices=[
                            ("topsoil", "Topsoil (0-10cm)"),
                            ("subsoil", "Subsoil (10-30cm)"),
                            ("deep", "Deep (30-50cm)"),
                            ("custom", "Custom Depth"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("depth_cm", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "soil_texture",
                    models.CharField(
                        choices=[
                            ("sand", "Sand"),
                            ("loam", "Loam"),
                            ("clay", "Clay"),
                            ("sandy_loam", "Sandy Loam"),
                            ("clay_loam", "Clay Loam"),
                            ("silt", "Silt"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bulk_density",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "soil_ph",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("lab_id", models.CharField(blank=True, max_length=50)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_samples",
                        to="collect.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["point_num"],
            },
        ),
        migrations.CreateModel(
            name="Transect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transect_id",
                    models.CharField(
                        choices=[
                            ("t1", "Transect 1 (NE-SW)"),
                            ("t2", "Transect 2 (NW-SE)"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("transect_num", models.IntegerField()),
                (
                    "start_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "end_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transects",
                        to="collect.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["transect_num"],
            },
        ),
        migrations.CreateModel(
            name="SpeciesObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_num", models.PositiveIntegerField(default=1)),
                (
                    "gps_waypoint_number",
                    models.PositiveIntegerField(
                        help_text="GPS waypoint for this observation point"
                    ),
                ),
                (
                    "bio_type",
                    models.CharField(
                        choices=[
                            ("tree", "Tree/Shrub"),
                            ("herb", "Herb/Forb"),
                            ("grass", "Grass"),
                            ("fern", "Fern"),
                            ("animal_sign", "Animal Sign"),
                            ("invasive", "Invasive Species"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("acacia_karroo", "Acacia karroo (Soetdoring)"),
                            ("acacia_mearnsii", "Acacia mearnsii (Black Wattle)"),
                            (
                                "afrocarpus_falcatus",
                                "Afrocarpus falcatus (Outeniqua Yellowwood)",
                            ),
                            ("brabejum", "Brabejum stellatifolium (Wild Almond)"),
                            ("celtis_africana", "Celtis africana (White Stinkwood)"),
                            ("euphorbia", "Euphorbia spp."),
                            ("ficus", "Ficus spp. (Wild Fig)"),
                            ("ilex_mitis", "Ilex mitis (African Holly)"),
                            ("olea_capensis", "Olea capensis (Ironwood)"),
                            ("podocarpus", "Podocarpus latifolius (Real Yellowwood)"),
                            ("prunus_africana", "Prunus africana (Red Stinkwood)"),
                            ("virgilia", "Virgilia oroboides (Blossom Tree)"),
                            ("invasive_wattle", "Invasive Acacia spp."),
                            ("eucalyptus", "Eucalyptus spp."),
                            ("pine", "Pinus spp."),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("abundance", models.IntegerField()),
                (
                    "threat_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lc", "Least Concern (LC)"),
                            ("nt", "Near Threatened (NT)"),
                            ("vu", "Vulnerable (VU)"),
                            ("en", "Endangered (EN)"),
                            ("cr", "Critically Endangered (CR)"),
                            ("invasive", "Invasive/Alien"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dbh_bio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("north", "North (0)"),
                            ("northeast", "North-East (45)"),
                            ("east", "East (90)"),
                            ("southeast", "South-East (135)"),
                            ("south", "South (180)"),
                            ("southwest", "South-West (225)"),
                            ("west", "West (270)"),
                            ("northwest", "North-West (315)"),
                            ("flat", "Flat/No Aspect"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "landform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ridge", "Ridge/Crest"),
                            ("upper_slope", "Upper Slope"),
                            ("mid_slope", "Middle Slope"),
                            ("lower_slope", "Lower Slope"),
                            ("valley", "Valley/Footslope"),
                            ("plain", "Plain/Flat"),
                            ("depression", "Depression/Wetland"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "degradation_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None/Pristine"),
                            ("low", "Low - Minor disturbances"),
                            ("moderate", "Moderate - Some loss of function"),
                            ("high", "High - Significant degradation"),
                            ("severe", "Severe - Major rehabilitation needed"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "erosion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No visible erosion"),
                            ("sheet", "Sheet erosion (surface wash)"),
                            ("rill", "Rill erosion (small channels)"),
                            ("gully", "Gully erosion (large channels)"),
                            ("slump", "Slumping/mass movement"),
                            ("wind", "Wind erosion"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "water_distance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("less_100m", "Less than 100m"),
                            ("100_200m", "100-200m"),
                            ("200_500m", "200-500m"),
                            ("greater_500m", "Greater than 500m"),
                            ("no_water", "No permanent water nearby"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("micro_habitat_notes", models.TextField(blank=True)),
                (
                    "transect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_obs",
                        to="collect.transect",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrassBiomassSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_num", models.IntegerField()),
                (
                    "gps_waypoint_number",
                    models.PositiveIntegerField(
                        help_text="GPS waypoint for this grass sample point"
                    ),
                ),
                (
                    "grass_gps",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "grass_species",
                    models.CharField(
                        choices=[
                            ("loteropsis_semialata", "Loteropsis semialata"),
                            ("andropogon_eucomis", "Andropogon eucomis"),
                            ("bewsia_biflora", "Bewsia biflora"),
                            ("brachiaria_serrata", "Brachiaria serrata"),
                            ("cymbopogon_nardus", "Cymbopogon nardus"),
                            ("themeda_triandra", "Themeda triandra"),
                            ("heteropogon_contortus", "Heteropogon contortus"),
                            ("hyparrhenia_hirta", "Hyparrhenia hirta"),
                            ("megathyrsus_maximus", "Megathyrsus maximus"),
                            ("ehrharta_calycina", "Ehrharta calycina"),
                            ("mixed", "Mixed grass species"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("grass_weight", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "last_burned",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recent", "Recent (within 1 year)"),
                            ("1_2_years", "1-2 years ago"),
                            ("2_5_years", "2-5 years ago"),
                            ("more_5_years", "More than 5 years ago"),
                            ("never", "Never/No evidence of burning"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("grass_notes", models.TextField(blank=True)),
                (
                    "transect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grass_samples",
                        to="collect.transect",
                    ),
                ),
            ],
            options={
                "ordering": ["sample_num"],
            },
        ),
        migrations.CreateModel(
            name="TreeMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tree_id", models.CharField(max_length=20)),
                ("tree_num", models.IntegerField()),
                (
                    "gps_waypoint_number",
                    models.PositiveIntegerField(
                        help_text="GPS waypoint for this tree sample point"
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("acacia_karroo", "Acacia karroo (Soetdoring)"),
                            ("acacia_mearnsii", "Acacia mearnsii (Black Wattle)"),
                            (
                                "afrocarpus_falcatus",
                                "Afrocarpus falcatus (Outeniqua Yellowwood)",
                            ),
                            ("brabejum", "Brabejum stellatifolium (Wild Almond)"),
                            ("celtis_africana", "Celtis africana (White Stinkwood)"),
                            ("euphorbia", "Euphorbia spp."),
                            ("ficus", "Ficus spp. (Wild Fig)"),
                            ("ilex_mitis", "Ilex mitis (African Holly)"),
                            ("olea_capensis", "Olea capensis (Ironwood)"),
                            ("podocarpus", "Podocarpus latifolius (Real Yellowwood)"),
                            ("prunus_africana", "Prunus africana (Red Stinkwood)"),
                            ("virgilia", "Virgilia oroboides (Blossom Tree)"),
                            ("invasive_wattle", "Invasive Acacia spp."),
                            ("eucalyptus", "Eucalyptus spp."),
                            ("pine", "Pinus spp."),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tree_status",
                    models.CharField(
                        choices=[
                            ("live", "Live/Healthy"),
                            ("live_damaged", "Live/Damaged"),
                            ("dead_standing", "Dead Standing"),
                            ("dead_down", "Dead Down"),
                            ("stump", "Stump"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dbh", models.DecimalField(decimal_places=2, max_digits=6)),
                ("height", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "crown_width_n",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "crown_width_e",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "herbal_veg_present",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "herbal_veg_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "deadwood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "deadwood_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trees",
                        to="collect.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["tree_num"],
            },
        ),
        migrations.CreateModel(
            name="WaterAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "water_source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("perennial_river", "Perennial River"),
                            ("seasonal_river", "Seasonal River/Stream"),
                            ("spring", "Spring (Natural)"),
                            ("wetland", "Wetland/Marsh"),
                            ("dam_reservoir", "Dam/Reservoir"),
                            ("farm_dam", "Farm Dam"),
                            ("groundwater_borehole", "Groundwater/Borehole"),
                            ("rainwater_harvest", "Rainwater Harvesting"),
                            ("ephemeral_pan", "Ephemeral Pan/Vlei"),
                            ("no_water", "No Permanent Water Source"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("water_source_name", models.CharField(blank=True, max_length=100)),
                (
                    "water_source_gps",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "flow_regime",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("perennial", "Perennial (flows year-round)"),
                            ("intermittent", "Intermittent (seasonal flow)"),
                            ("ephemeral", "Ephemeral (flows only after rain)"),
                            ("dry", "Dry/No Flow Observed"),
                            ("regulated", "Regulated/Controlled (dam upstream)"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "seasonal_availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("permanent", "Permanent (available year-round)"),
                            ("seasonal_reliable", "Seasonal but Reliable"),
                            ("seasonal_unreliable", "Seasonal and Unreliable"),
                            ("drought_prone", "Drought-Prone (often dries up)"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "water_ph",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "water_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "water_turbidity_ntu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "electrical_conductivity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "water_quality_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent (pristine, potable)"),
                            ("good", "Good (minor impairments)"),
                            ("fair", "Fair (some pollution/impairment)"),
                            ("poor", "Poor (significantly impaired)"),
                            ("very_poor", "Very Poor (heavily polluted)"),
                            ("not_tested", "Not Field-Tested"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "riparian_veg_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pristine", "Pristine (intact natural vegetation)"),
                            ("good", "Good (minor disturbances)"),
                            ("moderate", "Moderate (some degradation)"),
                            ("degraded", "Degraded (significant loss)"),
                            (
                                "severely_degraded",
                                "Severely Degraded (bare/cultivated banks)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stream_bank_erosion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None (stable banks)"),
                            ("slight", "Slight (<10% bank affected)"),
                            ("moderate", "Moderate (10-30% bank affected)"),
                            ("severe", "Severe (30-60% bank affected)"),
                            ("very_severe", "Very Severe (>60% bank affected)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "wetland_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("floodplain", "Floodplain"),
                            ("depression", "Depression (endoreic basin)"),
                            ("channelled_valley", "Channelled Valley Bottom"),
                            ("hillslope_seep", "Hillslope Seep"),
                            ("pan", "Pan (endorheic depression)"),
                            ("estuarine", "Estuarine"),
                            ("none", "No Wetland Present"),
                            ("other", "Other (Specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "wetland_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unmodified", "Unmodified (natural/near-natural)"),
                            ("largely_natural", "Largely Natural"),
                            ("moderately_modified", "Moderately Modified"),
                            ("largely_modified", "Largely Modified"),
                            ("seriously_modified", "Seriously Modified"),
                            ("none", "No Wetland Present"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wetland_width_m", models.PositiveIntegerField(blank=True, null=True)),
                ("water_extraction_uses", models.CharField(blank=True, max_length=200)),
                (
                    "downstream_impacts",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None Observed"),
                            ("reduced_flow", "Reduced Downstream Flow"),
                            ("sedimentation", "Increased Sedimentation"),
                            ("pollution", "Pollution Transfer"),
                            ("erosion", "Downstream Erosion"),
                            ("wetland_loss", "Wetland Loss Downstream"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("water_notes", models.TextField(blank=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_assessment",
                        to="collect.plot",
                    ),
                ),
            ],
        ),
    ]
