# Generated by Django 5.0.14 on 2026-04-20 20:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("geojson", "GeoJSON"),
                            ("gpx", "GPX"),
                            ("kml", "KML"),
                            ("csv", "CSV"),
                            ("shapefile", "Shapefile (SHP/ZIP)"),
                        ],
                        default="geojson",
                        max_length=20,
                    ),
                ),
                ("geojson_data", models.JSONField(default=dict)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("color", models.CharField(default="#c4a84a", max_length=7)),
                ("visible", models.BooleanField(default=True)),
                ("feature_count", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_layers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["uploaded_by"], name="collect_upl_uploade_7d8c91_idx"
                    ),
                    models.Index(
                        fields=["layer_type"], name="collect_upl_layer_t_f36c96_idx"
                    ),
                    models.Index(
                        fields=["visible"], name="collect_upl_visible_016cc1_idx"
                    ),
                ],
            },
        ),
    ]
