# Generated by Django 5.0.14 on 2026-04-21 01:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0002_uploadedlayer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
